CREATE TABLE `hydra_oauth2_flow` (
  `login_challenge` varchar(40) NOT NULL,
  `login_verifier` varchar(40) NOT NULL,
  `login_csrf` varchar(40) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `request_url` text NOT NULL,
  `login_skip` tinyint(1) NOT NULL,
  `client_id` varchar(255) NOT NULL,
  `requested_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `login_initialized_at` timestamp NULL DEFAULT NULL,
  `oidc_context` json NOT NULL DEFAULT (_utf8mb4'{}'),
  `login_session_id` varchar(40),
  `state` smallint NOT NULL,
  `login_remember` tinyint(1) NOT NULL DEFAULT '0',
  `login_remember_for` int NOT NULL,
  `login_error` text,
  `acr` text NOT NULL DEFAULT (_utf8mb4''),
  `login_authenticated_at` timestamp NULL DEFAULT NULL,
  `login_was_used` tinyint(1) NOT NULL DEFAULT '0',
  `forced_subject_identifier` varchar(255) NOT NULL DEFAULT '',
  `context` json NOT NULL DEFAULT (_utf8mb4'{}'),
  `consent_challenge_id` varchar(40) DEFAULT NULL,
  `consent_skip` tinyint(1) NOT NULL DEFAULT '0',
  `consent_verifier` varchar(40) DEFAULT NULL,
  `consent_csrf` varchar(40) DEFAULT NULL,
  `consent_remember` tinyint(1) NOT NULL DEFAULT '0',
  `consent_remember_for` int DEFAULT NULL,
  `consent_handled_at` timestamp NULL DEFAULT NULL,
  `consent_error` text,
  `session_access_token` json NOT NULL DEFAULT (_utf8mb4'{}'),
  `session_id_token` json NOT NULL DEFAULT (_utf8mb4'{}'),
  `consent_was_used` tinyint(1) DEFAULT NULL,
  `nid` char(36) NOT NULL,
  `requested_scope` json NOT NULL,
  `requested_at_audience` json DEFAULT (_utf8mb4'[]'),
  `amr` json DEFAULT (_utf8mb4'[]'),
  `granted_scope` json DEFAULT NULL,
  `granted_at_audience` json DEFAULT (_utf8mb4'[]'),
  `login_extend_session_lifespan` tinyint(1) NOT NULL DEFAULT '0',
  `identity_provider_session_id` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`login_challenge`),
  UNIQUE KEY `hydra_oauth2_flow_consent_challenge_idx` (`consent_challenge_id`),
  KEY `hydra_oauth2_flow_login_session_id_idx` (`login_session_id`),
  KEY `hydra_oauth2_flow_nid_fk_idx` (`nid`),
  KEY `hydra_oauth2_flow_client_id_subject_idx` (`client_id`,`nid`,`subject`),
  KEY `hydra_oauth2_flow_sub_idx` (`subject`,`nid`),
  KEY `hydra_oauth2_flow_previous_consents_idx` (`subject`,`client_id`,`nid`,`consent_skip`,`consent_error`(2),`consent_remember`),
  CONSTRAINT `hydra_oauth2_flow_client_id_fk` FOREIGN KEY (`client_id`, `nid`) REFERENCES `hydra_client` (`id`, `nid`) ON DELETE CASCADE,
  CONSTRAINT `hydra_oauth2_flow_login_session_id_fk` FOREIGN KEY (`login_session_id`) REFERENCES `hydra_oauth2_authentication_session` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hydra_oauth2_flow_nid_fk_idx` FOREIGN KEY (`nid`) REFERENCES `networks` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `hydra_oauth2_flow_chk` CHECK (((`state` = 128) or (`state` = 129) or (`state` = 1) or ((`state` = 2) and (`login_remember` is not null) and (`login_remember_for` is not null) and (`login_error` is not null) and (`acr` is not null) and (`login_was_used` is not null) and (`context` is not null) and (`amr` is not null)) or ((`state` = 3) and (`login_remember` is not null) and (`login_remember_for` is not null) and (`login_error` is not null) and (`acr` is not null) and (`login_was_used` is not null) and (`context` is not null) and (`amr` is not null)) or ((`state` = 4) and (`login_remember` is not null) and (`login_remember_for` is not null) and (`login_error` is not null) and (`acr` is not null) and (`login_was_used` is not null) and (`context` is not null) and (`amr` is not null) and (`consent_challenge_id` is not null) and (`consent_verifier` is not null) and (`consent_skip` is not null) and (`consent_csrf` is not null)) or ((`state` = 5) and (`login_remember` is not null) and (`login_remember_for` is not null) and (`login_error` is not null) and (`acr` is not null) and (`login_was_used` is not null) and (`context` is not null) and (`amr` is not null) and (`consent_challenge_id` is not null) and (`consent_verifier` is not null) and (`consent_skip` is not null) and (`consent_csrf` is not null)) or ((`state` = 6) and (`login_remember` is not null) and (`login_remember_for` is not null) and (`login_error` is not null) and (`acr` is not null) and (`login_was_used` is not null) and (`context` is not null) and (`amr` is not null) and (`consent_challenge_id` is not null) and (`consent_verifier` is not null) and (`consent_skip` is not null) and (`consent_csrf` is not null) and (`granted_scope` is not null) and (`consent_remember` is not null) and (`consent_remember_for` is not null) and (`consent_error` is not null) and (`session_access_token` is not null) and (`session_id_token` is not null) and (`consent_was_used` is not null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci